[tool.poetry]
name = "galaxy"
version = "21.01"
description = "Galaxy is an open, web-based platform for accessible, reproducible, and transparent computational research."
authors = ["Galaxy Contributors"]
license = "AFL-3.0"
readme = "README.rst"
homepage = "https://galaxyproject.org/"
repository = "https://github.com/galaxyproject/galaxy/"
documentation = "https://docs.galaxyproject.org/"

[[tool.poetry.source]]
name = "galaxyproject"
url = "https://wheels.galaxyproject.org/simple"

[tool.poetry.dependencies]
aiofiles = "*"
async-generator = {version = "*", python = "~3.6"}
async-exit-stack = {version = "*", python = "~3.6"}
Babel = "*"
bdbag = "*"
Beaker = "1.11.0"
bioblend = "*"
bleach = "*"
boltons = "*"
boto = "*"
bx-python = "*"
celery = "*"
Cheetah3 = "*"
cloudauthz = "==0.6.0"
cloudbridge = "*"
contextvars = {version = "*", python = "~3.6"}
circus = "*"
cwltool = "==3.0.20201109103151"
dictobj = "*"
docutils = "!=0.17, !=0.17.1"
edam-ontology = "*"
Fabric3 = "*"
fastapi = ">=0.65.2"
fastapi-utils = "*"
fs = "*"
future = "*"
galaxy_sequence_utils = "*"
gxformat2 = "*"
h5py = "!=2.7.0, !=2.7.1"
isa-rwval = "*"
kombu = "*"
lagom = "<1.2.1"  # maximum recursion depth exceeded (on functional_tests run)
Mako = "*"
Markdown = "*"
MarkupSafe = "*"
Mercurial = "*"
mrcfile = "*"
nodeenv = "*"
nose = "*"
numpy = "*"
paramiko = "*"
Parsley = "*"
Paste = "*"
psutil = "*"
pulsar-galaxy-lib = ">=0.14.9"
pycryptodome = "*"
pykwalify = "*"
pyparsing = "*"
pysam = "*"
python = "^3.6"
pyuwsgi = "*"
PyYAML = "*"
refgenconf = ">=0.12.0"
requests = "*"
Routes = "*"
social-auth-core = {version = "==4.0.3", extras = ["openidconnect"]}
sortedcontainers = "*"
SQLAlchemy = ">=1.4.20,<2"
sqlalchemy-migrate = "*"
sqlitedict = "*"
sqlparse = "*"
starlette = "*"
starlette-context = {version = "*", python = ">=3.7"}
svgwrite = "*"
tifffile = "<=2020.9.3"  # Last version compatible with python 3.6
uvicorn = "*"
WebOb = "*"
Whoosh = "*"
zipstream-new = "*"

[tool.poetry.dev-dependencies]
fluent-logger = "*"
httpx = "*"
gunicorn = "*"
lxml = "!=4.2.2"
markdown-it-reporter = "*"
NoseHTML = "*"
pygithub = ">=1.54.1"  # prevent downgrade (depends on pyjwt(<2.0); pyjwt auto-upgrade to 2.0.1 causes pygithub downgrade to 1.53)
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-html = "*"
python-irodsclient = "*"
pytest-json-report = "*"
pytest-mock = "*"
pytest-pythonpath = "*"
pytest-postgresql = "*"
pytest-shard = "*"
recommonmark = "*"
responses = "*"
selenium = "*"
Sphinx = "*"
sphinx_markdown_tables = "*"
sphinx_rtd_theme = "*"
statsd = "*"
testfixtures = "*"
twill = "*"
watchdog = "*"
